services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: rafael
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    restart: always
    ports:
      - "3111:3111"
    environment:
      - DATABASE_URL=postgresql://rafael:mypassword@db:5432/mydb?schema=public
      - PORT=3111
      - JWT_KEY=your_secret_key_here
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - db
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
